"""initial

Revision ID: e876d71bda23
Revises: 
Create Date: 2026-03-04 07:51:51.573752
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = 'e876d71bda23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_skill_files_skill_id', table_name='skill_files')
    op.drop_table('skill_files')
    op.alter_column('skills', 'description_for_agent',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skills', 'description_for_agent',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.create_table('skill_files',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('is_entry', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name='skill_files_skill_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='skill_files_pkey')
    )
    op.create_index('ix_skill_files_skill_id', 'skill_files', ['skill_id'], unique=False)
    # ### end Alembic commands ###
