"""Add task decomposition and trigger fields

Revision ID: f57b946d3697
Revises: cb7567a39843
Create Date: 2026-03-06 22:57:16.090203
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = 'f57b946d3697'
down_revision: Union[str, None] = 'cb7567a39843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'filesystem_access',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('agents', 'system_access',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('agents', 'self_thinking',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_autonomous_runs_agent_id', table_name='autonomous_runs')
    op.drop_index('idx_autonomous_runs_status', table_name='autonomous_runs')
    op.alter_column('chat_messages', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('chat_sessions', 'protocol_state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('model_role_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('model_role_assignments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_model_role_assignments_model', table_name='model_role_assignments')
    op.drop_index('idx_model_role_assignments_role', table_name='model_role_assignments')
    op.add_column('tasks', sa.Column('execute_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('trigger_type', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('trigger_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tasks', sa.Column('parent_task_id', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('is_decomposed', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('tasks', sa.Column('ready_to_execute', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_task_id'], ['id'], ondelete='CASCADE')
    op.alter_column('thinking_protocols', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'standard'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('thinking_protocols', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'standard'::character varying"))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_column('tasks', 'ready_to_execute')
    op.drop_column('tasks', 'is_decomposed')
    op.drop_column('tasks', 'parent_task_id')
    op.drop_column('tasks', 'trigger_config')
    op.drop_column('tasks', 'trigger_type')
    op.drop_column('tasks', 'execute_at')
    op.create_index('idx_model_role_assignments_role', 'model_role_assignments', ['role'], unique=False)
    op.create_index('idx_model_role_assignments_model', 'model_role_assignments', ['model_config_id'], unique=False)
    op.alter_column('model_role_assignments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('model_role_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_sessions', 'protocol_state',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('chat_messages', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index('idx_autonomous_runs_status', 'autonomous_runs', ['status'], unique=False)
    op.create_index('idx_autonomous_runs_agent_id', 'autonomous_runs', ['agent_id'], unique=False)
    op.alter_column('agents', 'self_thinking',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('agents', 'system_access',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('agents', 'filesystem_access',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
